-- Add items to existing profiles or create your own to sell groups of items using alias commands
local profiles = {}

profiles['cp'] = S{
    'Royal Squire\'s Halberd',
    'Mercenary Captain\'s Scythe',
    'Centurion\'s Axe'
}
-- //sellnpc powder
profiles['powder'] = S{
    'prize powder',
}

-- //sellnpc junk
profiles['junk'] = S{
    'Earth Spirit',
    'Mithran Tomato',
    'Herb Seeds',
    'Little Worm',
    'Twitherym Wing',
    'Wind Cluster',
    'Carrier Crab Carapace',
    'Kazham Peppers',
    'Mhaura Garlic',
    'Vanilla',
    'Sage',
    'Deathball',
    'Voay Sword -1',
    'Black Pepper',
    'Habaneros',
    'Bay Leaves',
    'Akaso',
    'Kapor Log',
    'Bismuth Ore',
    'Fire Fewell',
    'Earth Fewell',
    'Water Fewell',
    'Wind Fewell',
    'Ice Fewell',
    'Lightning Fewell',
    'Dark Fewell',
    'Light Fewell',
    'Wind Crystal', 
    'Ice Crystal', 
    'Dark Crystal', 
    'Light Crystal', 
    'Fire Crystal', 
    'Water Crystal', 
    'Earth Crystal', 
    'Lightng. Crystal', 
    'Potion', 
    'Gugru Tuna', 
    'Cobalt Jellyfish', 
    'Shall Shell', 
    'Dragon Fruit', 
    'Gigant Squid', 
    'Bluetail', 
    'Mackerel', 
    'Moorish Idol', 
    'Grimmonite', 
    'Millioncorn', 
    'Kukuru Bean', 
    'Puffball', 
    'Sunflower Seeds', 
    'Poison Flour', 
    'Blue Peas', 
    'Kopparnickel Ore', 
    'Pugil Scales', 
    'Uragnite Shell', 
    'Ram Horn', 
    'Dragon Bone', 
    'Turtle Shell', 
    'Swamp Ore', 
    'Fish Bones', 
    'Aht Urhgan Brass', 
    'Iron Ore', 
    'Gold Ore', 
    'Pebble', 
    'Platinum Ore', 
    'H.Q. Scp. Shell', 
    'Bone Chip', 
    'Meteorite', 
    'Phrygian Ore', 
    'Zinc Ore', 
    'Elshimo Newt', 
    'Moat Carp', 
    'Copper Frog', 
    'Gavial Fish', 
    'Crescent Fish', 
    'Giant Catfish', 
    'Ca Cuong', 
    'Yorchete', 
    'Pamamas', 
    'Walnut', 
    'Guatambu Log', 
    'Chestnut Log', 
    'Arrowwood Log', 
    'Maple Log', 
    'Grove Cuttings', 
    'Walnut Log', 
    'Elm Log', 
    'Urunday Log', 
    'Dogwood Log', 
    'Mahogany Log', 
    'Felicifruit', 
    'King Locust', 
    'Yagudo Cherry', 
    'Persikos', 
    'Divine Log', 
    'Oak Log', 
    'El. Pachira Fruit', 
    'Flax Flower', 
    'Skull Locust', 
    'Wijnruit', 
    'Red Rose', 
    'Watermelon', 
    'Red Moko Grass', 
    'Dark Bass', 
    'Gold Carp', 
    'Black Eel', 
    'Igneous Rock', 
    'Snapping Mole', 
    'Darksteel Ore', 
    'Khroma Ore', 
    'Tin Ore', 
    'Scorpion Shell', 
    'H.Q. Crab Shell', 
    'Scorpion Claw', 
    'Marguerite', 
    'Ulbukan Lobster', 
    'Yayinbaligi', 
    'Pipira', 
    'Ruddy Seema', 
    'Eggplant', 
    'Saruta Cotton', 
    'Ulbuconut', 
    'Antlion Jaw', 
    'Copper Ore', 
    'Auric Sand', 
    'Dst. Nugget', 
    'Orichalcum Ore', 
    'Vanadium Ore', 
    'Voay Staff -1', 
    'Contortopus', 
    'Adoulinian Kelp', 
    'Black Prawn', 
    'Black Sole', 
    'Dragon Talon', 
    'Mythril Ore', 
    'Beetle Jaw', 
    'Crab Shell', 
    'Brass Loach', 
    'Rusty Bucket', 
    'Tree Cuttings', 
    'Ash Log', 
    'Spider Web', 
    'Fresh Marjoram', 
    'Yagudo Drink', 
    'Three-eyed Fish', 
    'Cone Calamary', 
    'Zebra Eel', 
    'Quus', 
    'Bastore Bream', 
    'Titanictus', 
    'Tarutaru Rice', 
    'Rye Flour', 
    'Adaman Ore', 
    'Crayfish', 
    'Lacquer Tree Log', 
    'Insect Wing', 
    'Rolanberry', 
    'Napa', 
    'Lesser Chigoe', 
    'Bloodblotch', 
    'Bat Fang', 
    'Ebony Log', 
    'Fresh Mugwort', 
    'Pine Nuts', 
    'Crawler Cocoon', 
    'Acorn', 
    'Black Ghost', 
    'Faerie Apple', 
    'Red Terrapin', 
    'Barnacle', 
    'Little Worm', 
    'Vegetable Seeds', 
    'Chestnut', 
    'Coral Fungus', 
    'Bhefhel Marlin', 
    'Dwarf Remora', 
    'Win. Tea Leaves', 
    'Sheep Tooth', 
    'Blk. Tiger Fang', 
    'Wootz Ore', 
    'Bugard Tusk', 
    'Loc. Elutriator', 
    'Senroh Sardine', 
    'Silver Ore', 
    'Green Rock', 
    'Giant Stinger', 
    'Burdock', 
    'La Theine Cbg.', 
    'Grain Seeds', 
    'Pumpkin Pie', 
    'Nopales', 
    'San d\'Or. Flour', 
    'Dryad Root', 
    'Crawler Egg', 
    'Semolina', 
    'Tiny Goldfish', 
    'Woozyshroom', 
    'Matsya', 
    'Dragonfish', 
    'Flint Stone', 
    'Velkk Necklace', 
    'Velkk Mask', 
    'Matamata Shell', 
    'Titanium Ore', 
    'Moko Grass', 
    'Emperor Fish', 
    'Isleracea', 
    'Cactus Stems', 
    'Wivre Maul',
    'Raptor Skin',
    'Peiste Skin',
    'Slime Juice',
    'Infinity Core',
    'Acheron Shield',    
    "Yagudo cherry",
    "Walnut",
    "Watermelon",
    "Bunch of wild pamamas",
    "Faded crystal",    
    "Pod of blue peas",
    "Lightning crystal",
    "Bag of San d'Orian flour",    
    "Scorpion claw",
    "Chunk of mythril ore",
    "Handful of pugil scales",
    "Dark crystal",
    "Bone chip",
    "Elshimo newt",
    "Rusty bucket",
    "Moat carp",
    "Dark bass",
    "Giant catfish",
    "Ice crystal",
    "Faerie apple",
    "Maple log",
    "Elm log",
    'Win. Tea Leaves',    
    'Tin Ore',
    'Ash Log',
    'Fresh Marjoram',
    'Grow-M-Good',
    'vegetable seeds',
    'Mhaura garlic',
    'light crystal',
    'auric sand',
    'fish bones',
    'fresh mugwort',
    'arrowwood log',
    'dogwood log',
    'felicifruit',
    'urunday log',
    'Elshimo pachira fruit',
    'walnut log',
    'lacquer tree log',
    'watermelon',
    'Brass Loach',
    'Elshimo Newt',
    'Gavial Fish',
    'Crescent Fish',
    'Fire Crystal',
    'Igneous Rock',
    'Gigant Squid',
    'Moorish Idol',
    'Veydal Wrasse',
    'Crawler Egg',
    'Burdock',
    'Yagudo Cherry',
    'Spider Web',
    'Walnut',
    'Dark Crystal',
    'Crawler Cocoon',
    'Faerie Apple',
    'Black Eel',
    'Dark Bass',
    'Light Crystal',
    'Auric Sand',
    'Khroma Ore',
    'Snapping Mole',
    'Bluetail',
    'Zebra Eel',
    'Zinc Ore',
    'Flint Stone',
    'Ice Crystal',
    'Elshimo newt',
    'Ulbukan lobster',
    'Rusty bucket',
    'Red terrapin',
    'Giant catfish',
    'Clot Plasma',
    'Wicca Subligar',
    'Diamond',
    'Metanoia Ring',
    'Coeurl Meat',
    'Buffalo Meat',
    'Emerald',
    'Scorpion Shell',
    'Hecteyes Eye',
    'Bifrost Ring',
    'Clionid Wing',
    'Spinel',
    'Ruby',
    'Thew Bomblet',
    'Topaz',
    'Sanguinet',
    'Tiresias\' Cape',
    'Humus',
    'Lithe Boots',
    'Artemis\'s Medal',
    'Gnat Wing',
    'Hoard Ring',
    'Angelstone',
    'Cockatrice Skin',
    'Cockatrice Meat',
    'Giant Bird Fthr.',
    'Dried Mugwort',
    'Wam. Cocoon',
    'mercury',
    'Slime Oil',
    'blk. tiger fang',
    'dragon blood',
    'magic pot shard',
    'marid hair',
    'puk wing',
    'Poroggo Hat',
    'manticore hair',
    'scorpion claw',
    'bone chip',
    'malboro vine',
    'imp wing',
    'sheep tooth',
    'wolf hide',
    'Eschalixir',
    'Eschalixir +1',
    'Snow Geode',
    'Leviatite',
    'Giant Femur',
    'Dhalmel Meat',
    'Shadow Geode',
    'Earth Crystal',
    'Water Crystal',
    'Wind Crystal',
    'Land Crab Meat',
    'Golden Shell',
    'chestnut',
    'san d\'Or. carrot',
    'Darksteel Ore',
    'Steel Ingot',
    'Mahogany Log',
    'Petrified Log',
    'Gold Ingot',
    'Durium Ore',
    'Jadeite',
    'Aquamarine',
    'Moonstone',
    'Sunstone',
    'Zircon',
    'Fluorite',
    'Ram Horn',
    'Phil. Stone',
    'Granite',
    'Darksteel Ingot',
    'Coral Fragment',
    'Phrygian Ore',
    'Mythril Ingot',
    'King Truffle',
    'Platinum Ore',
    'Imperial Cermet',
    'Wyvern Scales',
    'Wyvern Tailskin',
    'Khimaira Mane',
    'Anc. Beast Horn',
    'Behemoth Horn',
    'Beech Log',
    'Ebony Log',
    'Platinum Ingot',
    'Blue Rock',
    'Chrysoberyl',
    'Cerberus Meat',
    'Ruszor Meat',
    'Agility Potion',
    'Pro-Ether',
    'Pro-Ether +1',
    'Dexterity Potion',
    'Hi-Elixir',
    'Demon Horn',
    'Pro-Elixir',
    'Jacaranda Log',
    'Phoenix Feather',
    'Flocon-de-mer',
    'W. Spider\'s Web',
    'Painite',
    'Black Rock',
    'Green Rock',
    'Gold Ore',
    'Hi-Potion +2',
    'Hi-Potion +3',
    'X-Potion +2',
    'X-Potion +3',
    'Dragon Meat',
    'Mythril Ore',
    'Dragon Heart', 
    'Rainbow Cloth', 
    'Bird Feather',
    'Persikos',
    'Elixir',
    'Teak Log', 
    'Red Rock',
    'Translucent Rock',
    'Ram Skin',
    'Manticore Hide',
    'Int. Potion',
    'Emperor Fish',
    'Cashmere Wool',
    'Kitron',
    'Fiend Blood',
    'Bat Wing',
    'Bat Fang',
    'Aqua Geode',
    'Ifritite',
    'Carbite',
    'Ramuite',
    'Fenrite',
    'Beastman Blood',
    'Titanite',
    'Garudite',
    'Kejusu Satin',
    'Hydra Fang',
    'Cerberus Hide',
    'Thunder Geode',
    'Shivite',
    'Strength Potion',
    'Hydra Scale',
    'Bunch of Kazham peppers',
    'Quus',
    'Shall shell',
    'Senroh sardine',
    'Mackerel',
    'Barnacle',
    'Clump of Adoulinian kelp',
    'Clump of moko grass',
    'Flax flower',
    'Clump of red moko grass',
    'Copper frog',
    'Dryad root',
    'Chunk of copper ore',
    'Pebble',
    'Earth crystal',
    'Crayfish',
    'Moat carp',
    'Lightning crystal',
    'Handful of pine nuts',
    'Acorn',
    'Skull locust',
    'Contortopus',
    'Flame Geode',
    'Breeze Geode',
    'Soil Geode',
    'Light Geode',
    'Colibri Beak',
    'Colibri Feather',
    'Beetle Jaw',
    'Beetle Shell',
    'Insect Wing',
    'Semolina',
    'Puffball',
    'black sole',
    'Bastore bream',
    'grimmonite',
    'Bhefhel marlin',
    'Gugru tuna',
    'lesser chigoe',
    'eggplant',
    'wijnruit',
    'rolanberry',
    'bag of grove cuttings',
    'ca cuong',
    'bunch of Buburimu grapes',
    'cone calamary',
    'king locust',
    'meteorite',
    'orb of water fewell',
    'Derfland pear',
    'popoto',
    'head of Grauberg lettuce',
    'lilac',
    'ball of Saruta cotton',
    'bunch of pamamas',
    'yayinbaligi',
    'pipira',
    'cactus stems',
    'orb of lightning fewell',
    'kukuru bean',
    'coral fungus',
}

return profiles