-- Add items to existing profiles or create your own to sell groups of items using alias commands
local profiles = {}

profiles['cp'] = S{
    'Royal Squire\'s Halberd',
    'Mercenary Captain\'s Scythe',
    'Centurion\'s Axe'
}
-- //sellnpc powder
profiles['powder'] = S{
    'prize powder',
}

-- //sellnpc junk
profiles['junk'] = S{
    "Yagudo cherry",
    "Walnut",
    "Watermelon",
    "Bunch of wild pamamas",
    "Faded crystal",    
    "Pod of blue peas",
    "Lightning crystal",
    "Bag of San d'Orian flour",    
    "Scorpion claw",
    "Chunk of mythril ore",
    "Handful of pugil scales",
    "Dark crystal",
    "Bone chip",
    "Elshimo newt",
    "Rusty bucket",
    "Moat carp",
    "Dark bass",
    "Giant catfish",
    "Ice crystal",
    "Faerie apple",
    "Maple log",
    "Elm log",
    'Sage',
    'Habaneros',
    'Win. Tea Leaves',    
    'Tin Ore',
    'Ash Log',
    'Fresh Marjoram',
    'Grow-M-Good',
    'Windurstian Tea leave',
    'vegetable seed',
    'Mhaura garlic',
    'light crystal',
    'auric sand',
    'fish bone',
    'fresh mugwort',
    'arrowwood log',
    'dogwood log',
    'felicifruit',
    'urunday log',
    'Elshimo pachira fruit',
    'walnut log',
    'lacquer tree log',
    'walnuts',
    'watermelon',
    'spider webs',
    'Brass Loach',
    'Elshimo Newt',
    'Gavial Fish',
    'Crescent Fish',
    'Fire Crystal',
    'Igneous Rock',
    'Gigant Squid',
    'Moorish Idol',
    'Veydal Wrasse',
    'Crawler Egg',
    'Burdock',
    'Yagudo Cherry',
    'Spider Web',
    'Walnut',
    'Dark Crystal',
    'Crawler Cocoon',
    'Faerie Apple',
    'Black Eel',
    'Dark Bass',
    'Light Crystal',
    'Auric Sand',
    'Khroma Ore',
    'Snapping Mole',
    'Bluetail',
    'Zebra Eel',
    'Black Pepper',
    'Zinc Ore',
    'Flint Stone',
    'Ice Crystal',
    'Elshimo newt',
    'Ulbukan lobster',
    'Rusty bucket',
    'Red terrapin',
    'Giant catfish',
    'Clot Plasma',
    'Wicca Subligar',
    'Diamond',
    'Metanoia Ring',
    'Coeurl Meat',
    'Buffalo Meat',
    'Emerald',
    'Scorpion Shell',
    'Hecteyes Eye',
    'Bifrost Ring',
    'Clionid Wing',
    'Spinel',
    'Ruby',
    'Thew Bomblet',
    'Topaz',
    'Sanguinet',
    'Tiresias\' Cape',
    'Humus',
    'Lithe Boots',
    'Artemis\'s Medal',
    'Gnat Wing',
    'Hoard Ring',
    'Angelstone',
    'Cockatrice Skin',
    'Cockatrice Meat',
    'Giant Bird Fthr.',
    'Dried Mugwort',
    'Wam. Cocoon',
    'mercury',
    'Slime Oil',
    'blk. tiger fang',
    'dragon blood',
    'magic pot shard',
    'marid hair',
    'puk wing',
    'Poroggo Hat',
    'manticore hair',
    'scorpion claw',
    'bone chip',
    'malboro vine',
    'imp wing',
    'sheep tooth',
    'wolf hide',
    'Eschalixir',
    'Eschalixir +1',
    'Snow Geode',
    'Leviatite',
    'Giant Femur',
    'Dhalmel Meat',
    'Shadow Geode',
    'Earth Crystal',
    'Water Crystal',
    'Wind Crystal',
    'Land Crab Meat',
    'Golden Shell',
    'chestnut',
    'san d\'Or. carrot',
    'Darksteel Ore',
    'Steel Ingot',
    'Mahogany Log',
    'Petrified Log',
    'Gold Ingot',
    'Durium Ore',
    'Jadeite',
    'Aquamarine',
    'Moonstone',
    'Sunstone',
    'Zircon',
    'Fluorite',
    'Gold Thread',
    'Ram Horn',
    'Phil. Stone',
    'Granite',
    'Darksteel Ingot',
    'Coral Fragment',
    'Phrygian Ore',
    'Mythril Ingot',
    'King Truffle',
    'Platinum Ore',
    'Imperial Cermet',
    'Wyvern Scales',
    'Wyvern Tailskin',
    'Khimaira Mane',
    'Anc. Beast Horn',
    'Behemoth Horn',
    'Beech Log',
    'Ebony Log',
    'Platinum Ingot',
    'Blue Rock',
    'Chrysoberyl',
    'Cerberus Meat',
    'Ruszor Meat',
    'Agility Potion',
    'Pro-Ether',
    'Pro-Ether +1',
    'Dexterity Potion',
    'Hi-Elixir',
    'Demon Horn',
    'Pro-Elixir',
    'Jacaranda Log',
    'Phoenix Feather',
    'Flocon-de-mer',
    'W. Spider\'s Web',
    'Painite',
    'Black Rock',
    'Green Rock',
    'Gold Ore',
    'Hi-Potion +2',
    'Hi-Potion +3',
    'X-Potion +2',
    'X-Potion +3',
    'Dragon Meat',
    'Mythril Ore',
    'Dragon Heart', 
    'Rainbow Cloth', 
    'Bird Feather',
    'Persikos',
    'Elixir',
    'Teak Log', 
    'Red Rock',
    'Translucent Rock',
    'Ram Skin',
    'Manticore Hide',
    'Int. Potion',
    'Emperor Fish',
    'Cashmere Wool',
    'Kitron',
    'Fiend Blood',
    'Bat Wing',
    'Bat Fang',
    'Aqua Geode',
    'Ifritite',
    'Carbite',
    'Ramuite',
    'Fenrite',
    'Beastman Blood',
    'Titanite',
    'Garudite',
    'Kejusu Satin',
    'Hydra Fang',
    'Cerberus Hide',
    'Thunder Geode',
    'Shivite',
    'Strength Potion',
    'Hydra Scale',
    'Deathball',
    'Bunch of Kazham peppers',
    'Quus',
    'Shall shell',
    'Senroh sardine',
    'Mackerel',
    'Barnacle',
    'Clump of Adoulinian kelp',
    'Clump of moko grass',
    'Flax flower',
    'Clump of red moko grass',
    'Copper frog',
    'Dryad root',
    'Chunk of copper ore',
    'Pebble',
    'Earth crystal',
    'Crayfish',
    'Moat carp',
    'Lightning crystal',
    'Handful of pine nuts',
    'Acorn',
    'Skull locust',
    'Contortopus',
    'Flame Geode',
    'Breeze Geode',
    'Soil Geode',
    'Light Geode',
    'Colibri Beak',
    'Colibri Feather',
    'Beetle Jaw',
    'Beetle Shell',
    'Insect Wing',
    'Semolina',
    'Puffball',
    'Millicorn',
}

return profiles