-- Generated by the Organizer Library (Sat Jun  3 22:37:01 2023)
return {
    [1]={
        ["log_name"]="assiduity pants +1", 
        ["id"]=28135, 
        ["name"]="assid. pants +1", 
        ["count"]=1
    }, 
    [2]={
        ["log_name"]="nourishing earring +1", 
        ["id"]=28485, 
        ["name"]="nourish. earring +1", 
        ["count"]=1
    }, 
    [3]={
        ["log_name"]="aurist's cape +1", 
        ["id"]=27620, 
        ["name"]="aurist's cape +1", 
        ["count"]=1
    }, 
    [4]={
        ["log_name"]="ebers pantaloons +2", 
        ["id"]=23288, 
        ["name"]="ebers pant. +2", 
        ["count"]=1
    }, 
    [5]={
        ["log_name"]="gelatinous ring +1", 
        ["id"]=10769, 
        ["name"]="gelatinous ring +1", 
        ["count"]=1
    }, 
    [6]={
        ["log_name"]="shneddick ring", 
        ["id"]=27590, 
        ["name"]="shneddick ring", 
        ["count"]=1
    }, 
    [7]={
        ["log_name"]="odnowa earring +1", 
        ["id"]=27549, 
        ["name"]="odnowa earring +1", 
        ["count"]=1
    }, 
    [8]={
        ["log_name"]="alaunus's cape", 
        ["id"]=26248, 
        ["name"]="alaunus's cape", 
        ["count"]=1
    }, 
    [9]={
        ["log_name"]="ebers bliaut +2", 
        ["id"]=23154, 
        ["name"]="ebers bliaut +2", 
        ["count"]=1
    }, 
    [10]={
        ["log_name"]="chironic hose", 
        ["id"]=25844, 
        ["name"]="chironic hose", 
        ["count"]=1
    }, 
    [11]={
        ["log_name"]="prolix ring", 
        ["id"]=10752, 
        ["name"]="prolix ring", 
        ["count"]=1
    }, 
    [12]={
        ["log_name"]="malignance pole", 
        ["id"]=22087, 
        ["name"]="malignance pole", 
        ["count"]=1
    }, 
    [13]={
        ["log_name"]="ebers cap +2", 
        ["id"]=23087, 
        ["name"]="ebers cap +2", 
        ["count"]=1
    }, 
    [14]={
        ["log_name"]="theophany bliaut +1", 
        ["id"]=27830, 
        ["name"]="theo. bliaut +1", 
        ["count"]=1
    }, 
    [15]={
        ["log_name"]="mephitas's ring", 
        ["id"]=27558, 
        ["name"]="mephitas's ring", 
        ["count"]=1
    }, 
    [16]={
        ["log_name"]="lebeche ring", 
        ["id"]=28538, 
        ["name"]="lebeche ring", 
        ["count"]=1
    }, 
    [17]={
        ["log_name"]="enki strap", 
        ["id"]=22213, 
        ["name"]="enki strap", 
        ["count"]=1
    }, 
    [18]={
        ["log_name"]="hygieia clogs +1", 
        ["id"]=27408, 
        ["name"]="hygieia clogs +1", 
        ["count"]=1
    }, 
    [19]={
        ["log_name"]="theophany pantaloons +1", 
        ["id"]=28113, 
        ["name"]="theo. pant. +1", 
        ["count"]=1
    }, 
    [20]={
        ["log_name"]="regal pumps +1", 
        ["id"]=28274, 
        ["name"]="regal pumps +1", 
        ["count"]=1
    }, 
    [21]={
        ["log_name"]="daybreak", 
        ["id"]=22040, 
        ["name"]="daybreak", 
        ["count"]=1
    }, 
    [22]={
        ["log_name"]="theophany mitts +1", 
        ["id"]=27966, 
        ["name"]="theo. mitts +1", 
        ["count"]=1
    }, 
    [23]={
        ["log_name"]="theophany cap +1", 
        ["id"]=27686, 
        ["name"]="theo. cap +1", 
        ["count"]=1
    }, 
    [24]={
        ["log_name"]="ethereal earring", 
        ["id"]=15965, 
        ["name"]="ethereal earring", 
        ["count"]=1
    }, 
    [25]={
        ["log_name"]="embla sash", 
        ["id"]=26354, 
        ["name"]="embla sash", 
        ["count"]=1
    }, 
    [26]={
        ["log_name"]="ebers earring +1", 
        ["id"]=25433, 
        ["name"]="ebers earring +1", 
        ["count"]=1
    }, 
    [27]={
        ["log_name"]="acuity belt +1", 
        ["id"]=28430, 
        ["name"]="acuity belt +1", 
        ["count"]=1
    }, 
    [28]={
        ["log_name"]="theophany duckbills +1", 
        ["id"]=28246, 
        ["name"]="theo. duckbills +1", 
        ["count"]=1
    }, 
    [29]={
        ["log_name"]="ghastly tathlum +1", 
        ["id"]=21344, 
        ["name"]="ghastly tathlum +1", 
        ["count"]=1
    }, 
    [30]={
        ["log_name"]="mizukage-no-kubikazari", 
        ["id"]=28379, 
        ["name"]="mizu. kubikazari", 
        ["count"]=1
    }, 
    [31]={
        ["log_name"]="ebers duckbills +2", 
        ["id"]=23355, 
        ["name"]="ebers duckbills +2", 
        ["count"]=1
    }, 
    [32]={
        ["log_name"]="sors shield", 
        ["id"]=28658, 
        ["name"]="sors shield", 
        ["count"]=1
    }, 
    [33]={
        ["log_name"]="battlecast gaiters", 
        ["id"]=28292, 
        ["name"]="battlecast gaiters", 
        ["count"]=1
    }
}