-- Generated by the Organizer Library (Wed May 31 19:37:04 2023)
return {
    [1]={
        ["log_name"]="gelatinous ring +1", 
        ["id"]=10769, 
        ["name"]="gelatinous ring +1", 
        ["count"]=1
    }, 
    [2]={
        ["log_name"]="agoge lorica +1", 
        ["id"]=26801, 
        ["name"]="agoge lorica +1", 
        ["count"]=1
    }, 
    [3]={
        ["log_name"]="ginsen", 
        ["id"]=21371, 
        ["name"]="ginsen", 
        ["count"]=1
    }, 
    [4]={
        ["log_name"]="agoge calligae +1", 
        ["id"]=27329, 
        ["name"]="agoge calligae +1", 
        ["count"]=1
    }, 
    [5]={
        ["log_name"]="sulevia's leggings +2", 
        ["id"]=25946, 
        ["name"]="sulev. leggings +2", 
        ["count"]=1
    }, 
    [6]={
        ["log_name"]="agoge mufflers +1", 
        ["id"]=26977, 
        ["name"]="agoge mufflers +1", 
        ["count"]=1
    }, 
    [7]={
        ["log_name"]="boii mufflers +2", 
        ["id"]=23219, 
        ["name"]="boii mufflers +2", 
        ["count"]=1
    }, 
    [8]={
        ["log_name"]="boii mask +2", 
        ["id"]=23085, 
        ["name"]="boii mask +2", 
        ["count"]=1
    }, 
    [9]={
        ["log_name"]="agoge mask +1", 
        ["id"]=26625, 
        ["name"]="agoge mask +1", 
        ["count"]=1
    }, 
    [10]={
        ["log_name"]="blurred shield +1", 
        ["id"]=27644, 
        ["name"]="blurred shield +1", 
        ["count"]=1
    }, 
    [11]={
        ["log_name"]="agoge cuisses +1", 
        ["count"]=1, 
        ["id"]=27153, 
        ["name"]="agoge cuisses +1", 
        ["augments"]={
            [1]="Enhances \"Warrior's Charge\" effect"
        }
    }, 
    [12]={
        ["log_name"]="boii cuisses +2", 
        ["id"]=23286, 
        ["name"]="boii cuisses +2", 
        ["count"]=1
    }, 
    [13]={
        ["log_name"]="boii lorica +2", 
        ["id"]=23152, 
        ["name"]="boii lorica +2", 
        ["count"]=1
    }, 
    [14]={
        ["log_name"]="ethereal earring", 
        ["id"]=15965, 
        ["name"]="ethereal earring", 
        ["count"]=1
    }, 
    [15]={
        ["log_name"]="shneddick ring", 
        ["id"]=27590, 
        ["name"]="shneddick ring", 
        ["count"]=1
    }, 
    [16]={
        ["log_name"]="lugra earring", 
        ["id"]=28481, 
        ["name"]="lugra earring", 
        ["count"]=1
    }, 
    [17]={
        ["log_name"]="naegling", 
        ["id"]=21621, 
        ["name"]="naegling", 
        ["count"]=1
    }
}