-- Generated by the Organizer Library (Mon Apr 17 06:44:17 2023)
return {
    [1]={
        ["log_name"]="ygnas's resolve +1", 
        ["id"]=28368, 
        ["name"]="ygnas's resolve +1", 
        ["count"]=1
    }, 
    [2]={
        ["log_name"]="odyssean greaves", 
        ["id"]=27494, 
        ["name"]="odyssean greaves", 
        ["count"]=1
    }, 
    [3]={
        ["log_name"]="agitator's collar", 
        ["id"]=28389, 
        ["name"]="agitator's collar", 
        ["count"]=1
    }
}