-- Generated by the Organizer Library (Sat Jun  3 22:37:01 2023)
return {
    [1]={
        ["log_name"]="ygnas's resolve +1", 
        ["id"]=28368, 
        ["name"]="ygnas's resolve +1", 
        ["count"]=1
    }, 
    [2]={
        ["log_name"]="nyame helm", 
        ["id"]=23761, 
        ["name"]="nyame helm", 
        ["count"]=1
    }, 
    [3]={
        ["log_name"]="nyame sollerets", 
        ["id"]=23789, 
        ["name"]="nyame sollerets", 
        ["count"]=1
    }, 
    [4]={
        ["log_name"]="combatant's torque", 
        ["id"]=26015, 
        ["name"]="combatant's torque", 
        ["count"]=1
    }, 
    [5]={
        ["log_name"]="sanctity necklace", 
        ["id"]=26023, 
        ["name"]="sanctity necklace", 
        ["count"]=1
    }, 
    [6]={
        ["log_name"]="amar cluster", 
        ["id"]=22262, 
        ["name"]="amar cluster", 
        ["count"]=1
    }, 
    [7]={
        ["log_name"]="nyame flanchard", 
        ["id"]=23782, 
        ["name"]="nyame flanchard", 
        ["count"]=1
    }, 
    [8]={
        ["log_name"]="famine sash", 
        ["id"]=28422, 
        ["name"]="famine sash", 
        ["count"]=1
    }, 
    [9]={
        ["log_name"]="petrov ring", 
        ["id"]=10772, 
        ["name"]="petrov ring", 
        ["count"]=1
    }, 
    [10]={
        ["log_name"]="nyame mail", 
        ["id"]=23768, 
        ["name"]="nyame mail", 
        ["count"]=1
    }, 
    [11]={
        ["log_name"]="moonshade earring", 
        ["id"]=11697, 
        ["name"]="moonshade earring", 
        ["count"]=1
    }, 
    [12]={
        ["log_name"]="eschan stone", 
        ["id"]=28415, 
        ["name"]="eschan stone", 
        ["count"]=1
    }, 
    [13]={
        ["log_name"]="malignance earring", 
        ["id"]=26088, 
        ["name"]="malignance earring", 
        ["count"]=1
    }, 
    [14]={
        ["log_name"]="aptitude mantle", 
        ["id"]=27603, 
        ["name"]="aptitude mantle", 
        ["count"]=1
    }, 
    [15]={
        ["log_name"]="loricate torque +1", 
        ["id"]=26002, 
        ["name"]="loricate torque +1", 
        ["count"]=1
    }, 
    [16]={
        ["log_name"]="cessance earring", 
        ["id"]=27541, 
        ["name"]="cessance earring", 
        ["count"]=1
    }, 
    [17]={
        ["log_name"]="nyame gauntlets", 
        ["id"]=23775, 
        ["name"]="nyame gauntlets", 
        ["count"]=1
    }, 
    [18]={
        ["log_name"]="warp ring", 
        ["id"]=28540, 
        ["name"]="warp ring", 
        ["count"]=1
    }
}