-- Generated by the Organizer Library (Wed May 31 19:37:04 2023)
return {
    [1]={
        ["log_name"]="firangi", 
        ["id"]=20678, 
        ["name"]="firangi", 
        ["count"]=1
    }, 
    [2]={
        ["log_name"]="ygnas's resolve +1", 
        ["id"]=28368, 
        ["name"]="ygnas's resolve +1", 
        ["count"]=1
    }, 
    [3]={
        ["log_name"]="cessance earring", 
        ["id"]=27541, 
        ["name"]="cessance earring", 
        ["count"]=1
    }, 
    [4]={
        ["log_name"]="pummeler's lorica +2", 
        ["id"]=23107, 
        ["name"]="pumm. lorica +2", 
        ["count"]=1
    }, 
    [5]={
        ["log_name"]="nyame helm", 
        ["id"]=23761, 
        ["name"]="nyame helm", 
        ["count"]=1
    }, 
    [6]={
        ["log_name"]="pummeler's mask +2", 
        ["id"]=23040, 
        ["name"]="pummeler's mask +2", 
        ["count"]=1
    }, 
    [7]={
        ["log_name"]="seething bomblet +1", 
        ["id"]=22255, 
        ["name"]="seeth. bomblet +1", 
        ["count"]=1
    }, 
    [8]={
        ["log_name"]="nyame sollerets", 
        ["id"]=23789, 
        ["name"]="nyame sollerets", 
        ["count"]=1
    }, 
    [9]={
        ["log_name"]="combatant's torque", 
        ["id"]=26015, 
        ["name"]="combatant's torque", 
        ["count"]=1
    }, 
    [10]={
        ["log_name"]="pummeler's mufflers +2", 
        ["id"]=23174, 
        ["name"]="pumm. mufflers +2", 
        ["count"]=1
    }, 
    [11]={
        ["log_name"]="cichol's mantle", 
        ["count"]=1, 
        ["id"]=26246, 
        ["name"]="cichol's mantle", 
        ["augments"]={
            [1]="DEX+20", 
            [2]="Accuracy+20 Attack+20", 
            [3]="Accuracy+10", 
            [4]="\"Dbl.Atk.\"+10", 
            [5]="Phys. dmg. taken-10%"
        }
    }, 
    [12]={
        ["log_name"]="duplus grip", 
        ["id"]=18820, 
        ["name"]="duplus grip", 
        ["count"]=1
    }, 
    [13]={
        ["log_name"]="nyame flanchard", 
        ["id"]=23782, 
        ["name"]="nyame flanchard", 
        ["count"]=1
    }, 
    [14]={
        ["log_name"]="montante +1", 
        ["id"]=21689, 
        ["name"]="montante +1", 
        ["count"]=1
    }, 
    [15]={
        ["log_name"]="thrud earring", 
        ["id"]=26107, 
        ["name"]="thrud earring", 
        ["count"]=1
    }, 
    [16]={
        ["log_name"]="sailfi belt +1", 
        ["id"]=28428, 
        ["name"]="sailfi belt +1", 
        ["count"]=1
    }, 
    [17]={
        ["log_name"]="petrov ring", 
        ["id"]=10772, 
        ["name"]="petrov ring", 
        ["count"]=1
    }, 
    [18]={
        ["log_name"]="shining one", 
        ["id"]=21883, 
        ["name"]="shining one", 
        ["count"]=1
    }, 
    [19]={
        ["log_name"]="nyame mail", 
        ["id"]=23768, 
        ["name"]="nyame mail", 
        ["count"]=1
    }, 
    [20]={
        ["log_name"]="flamma ring", 
        ["id"]=26211, 
        ["name"]="flamma ring", 
        ["count"]=1
    }, 
    [21]={
        ["log_name"]="moonshade earring", 
        ["id"]=11697, 
        ["name"]="moonshade earring", 
        ["count"]=1
    }, 
    [22]={
        ["log_name"]="fortified ring", 
        ["id"]=10773, 
        ["name"]="fortified ring", 
        ["count"]=1
    }, 
    [23]={
        ["log_name"]="sanctity necklace", 
        ["id"]=26023, 
        ["name"]="sanctity necklace", 
        ["count"]=1
    }, 
    [24]={
        ["log_name"]="boii earring", 
        ["id"]=25420, 
        ["name"]="boii earring", 
        ["count"]=1
    }, 
    [25]={
        ["log_name"]="lycurgos", 
        ["id"]=21779, 
        ["name"]="lycurgos", 
        ["count"]=1
    }, 
    [26]={
        ["log_name"]="pummeler's calligae +2", 
        ["id"]=23308, 
        ["name"]="pumm. calligae +2", 
        ["count"]=1
    }, 
    [27]={
        ["log_name"]="pummeler's cuisses +2", 
        ["id"]=23241, 
        ["name"]="pumm. cuisses +2", 
        ["count"]=1
    }, 
    [28]={
        ["log_name"]="nyame gauntlets", 
        ["id"]=23775, 
        ["name"]="nyame gauntlets", 
        ["count"]=1
    }
}