-- Generated by the Organizer Library (Sun Jul 23 06:33:37 2023)
return {
    [1]={
        ["log_name"]="cessance earring", 
        ["id"]=27541, 
        ["name"]="cessance earring", 
        ["count"]=1
    }, 
    [2]={
        ["log_name"]="cornelia's ring", 
        ["id"]=26227, 
        ["name"]="cornelia's ring", 
        ["count"]=1
    }, 
    [3]={
        ["log_name"]="nyame helm", 
        ["id"]=23761, 
        ["name"]="nyame helm", 
        ["count"]=1
    }, 
    [4]={
        ["log_name"]="pummeler's mufflers +3", 
        ["id"]=23509, 
        ["name"]="pumm. mufflers +3", 
        ["count"]=1
    }, 
    [5]={
        ["log_name"]="sakpata's leggings", 
        ["id"]=23785, 
        ["name"]="sakpata's leggings", 
        ["count"]=1
    }, 
    [6]={
        ["log_name"]="pummeler's lorica +3", 
        ["id"]=23442, 
        ["name"]="pumm. lorica +3", 
        ["count"]=1
    }, 
    [7]={
        ["log_name"]="throwing tomahawk", 
        ["id"]=18258, 
        ["name"]="thr. tomahawk", 
        ["count"]=1
    }, 
    [8]={
        ["log_name"]="pummeler's mask +3", 
        ["id"]=23375, 
        ["name"]="pummeler's mask +3", 
        ["count"]=1
    }, 
    [9]={
        ["log_name"]="coiste bodhar", 
        ["id"]=21431, 
        ["name"]="coiste bodhar", 
        ["count"]=1
    }, 
    [10]={
        ["log_name"]="sakpata's breastplate", 
        ["id"]=23764, 
        ["name"]="sakpata's plate", 
        ["count"]=1
    }, 
    [11]={
        ["log_name"]="warrior's bead necklace +2", 
        ["id"]=25419, 
        ["name"]="war. beads +2", 
        ["count"]=1
    }, 
    [12]={
        ["log_name"]="sailfi belt +1", 
        ["id"]=28428, 
        ["name"]="sailfi belt +1", 
        ["count"]=1
    }, 
    [13]={
        ["log_name"]="moonshade earring", 
        ["id"]=11697, 
        ["name"]="moonshade earring", 
        ["count"]=1
    }, 
    [14]={
        ["log_name"]="flamma gambieras +2", 
        ["id"]=25953, 
        ["name"]="flam. gambieras +2", 
        ["count"]=1
    }, 
    [15]={
        ["log_name"]="firangi", 
        ["id"]=20678, 
        ["name"]="firangi", 
        ["count"]=1
    }, 
    [16]={
        ["log_name"]="ygnas's resolve +1", 
        ["id"]=28368, 
        ["name"]="ygnas's resolve +1", 
        ["count"]=1
    }, 
    [17]={
        ["log_name"]="pummeler's calligae +3", 
        ["id"]=23643, 
        ["name"]="pumm. calligae +3", 
        ["count"]=1
    }, 
    [18]={
        ["log_name"]="montante +1", 
        ["id"]=21689, 
        ["name"]="montante +1", 
        ["count"]=1
    }, 
    [19]={
        ["log_name"]="fortified ring", 
        ["id"]=10773, 
        ["name"]="fortified ring", 
        ["count"]=1
    }, 
    [20]={
        ["log_name"]="combatant's torque", 
        ["id"]=26015, 
        ["name"]="combatant's torque", 
        ["count"]=1
    }, 
    [21]={
        ["log_name"]="sakpata's cuisses", 
        ["id"]=23778, 
        ["name"]="sakpata's cuisses", 
        ["count"]=1
    }, 
    [22]={
        ["log_name"]="pummeler's cuisses +3", 
        ["id"]=23576, 
        ["name"]="pumm. cuisses +3", 
        ["count"]=1
    }, 
    [23]={
        ["log_name"]="loxotic mace +1", 
        ["id"]=21091, 
        ["name"]="loxotic mace +1", 
        ["count"]=1
    }, 
    [24]={
        ["log_name"]="petrov ring", 
        ["id"]=10772, 
        ["name"]="petrov ring", 
        ["count"]=1
    }, 
    [25]={
        ["log_name"]="boii earring", 
        ["id"]=25420, 
        ["name"]="boii earring", 
        ["count"]=1
    }, 
    [26]={
        ["log_name"]="shining one", 
        ["id"]=21883, 
        ["name"]="shining one", 
        ["count"]=1
    }, 
    [27]={
        ["log_name"]="flamma dirs +2", 
        ["id"]=25886, 
        ["name"]="flamma dirs +2", 
        ["count"]=1
    }, 
    [28]={
        ["log_name"]="sakpata's helm", 
        ["id"]=23757, 
        ["name"]="sakpata's helm", 
        ["count"]=1
    }, 
    [29]={
        ["log_name"]="thrud earring", 
        ["id"]=26107, 
        ["name"]="thrud earring", 
        ["count"]=1
    }, 
    [30]={
        ["log_name"]="platinum moogle belt", 
        ["id"]=26366, 
        ["name"]="plat. mog. belt", 
        ["count"]=1
    }, 
    [31]={
        ["log_name"]="flamma ring", 
        ["id"]=26211, 
        ["name"]="flamma ring", 
        ["count"]=1
    }, 
    [32]={
        ["log_name"]="sakpata's gauntlets", 
        ["id"]=23771, 
        ["name"]="sakpata's gauntlets", 
        ["count"]=1
    }, 
    [33]={
        ["log_name"]="sanctity necklace", 
        ["id"]=26023, 
        ["name"]="sanctity necklace", 
        ["count"]=1
    }, 
    [34]={
        ["log_name"]="lycurgos", 
        ["id"]=21779, 
        ["name"]="lycurgos", 
        ["count"]=1
    }, 
    [35]={
        ["log_name"]="utu grip", 
        ["id"]=22212, 
        ["name"]="utu grip", 
        ["count"]=1
    }, 
    [36]={
        ["log_name"]="cichol's mantle", 
        ["count"]=1, 
        ["id"]=26246, 
        ["name"]="cichol's mantle", 
        ["augments"]={
            [1]="VIT+20", 
            [2]="Accuracy+20 Attack+20", 
            [3]="VIT+10", 
            [4]="Weapon skill damage +10%"
        }
    }, 
    [37]={
        ["log_name"]="cichol's mantle", 
        ["count"]=1, 
        ["id"]=26246, 
        ["name"]="cichol's mantle", 
        ["augments"]={
            [1]="DEX+20", 
            [2]="Accuracy+20 Attack+20", 
            [3]="Accuracy+10", 
            [4]="\"Dbl.Atk.\"+10", 
            [5]="Phys. dmg. taken-10%"
        }
    }
}