-- Generated by the Organizer Library (Sat Apr 13 07:04:31 2024)
return {
    [1]={
        ["log_name"]="loquacious earring", 
        ["id"]=14812, 
        ["name"]="loquac. earring", 
        ["count"]=1
    }, 
    [2]={
        ["log_name"]="bunzi's rod", 
        ["id"]=22041, 
        ["name"]="bunzi's rod", 
        ["count"]=1
    }, 
    [3]={
        ["log_name"]="sroda tathlum", 
        ["id"]=22301, 
        ["name"]="sroda tathlum", 
        ["count"]=1
    }, 
    [4]={
        ["log_name"]="moonlight cape", 
        ["id"]=26269, 
        ["name"]="moonlight cape", 
        ["count"]=1
    }, 
    [5]={
        ["log_name"]="regal cuffs", 
        ["id"]=25827, 
        ["name"]="regal cuffs", 
        ["count"]=1
    }, 
    [6]={
        ["log_name"]="bunzi's gloves", 
        ["id"]=23774, 
        ["name"]="bunzi's gloves", 
        ["count"]=1
    }, 
    [7]={
        ["log_name"]="erra pendant", 
        ["id"]=26030, 
        ["name"]="erra pendant", 
        ["count"]=1
    }, 
    [8]={
        ["log_name"]="pixie hairpin +1", 
        ["id"]=26696, 
        ["name"]="pixie hairpin +1", 
        ["count"]=1
    }
}