-- Generated by the Organizer Library (Mon Apr 17 06:44:17 2023)
return {
    [1]={
        ["log_name"]="flamma dirs +2", 
        ["id"]=25886, 
        ["name"]="flamma dirs +2", 
        ["count"]=1
    }, 
    [2]={
        ["log_name"]="flamma korazin +2", 
        ["id"]=25797, 
        ["name"]="flamma korazin +2", 
        ["count"]=1
    }, 
    [3]={
        ["log_name"]="flamma ring", 
        ["id"]=26211, 
        ["name"]="flamma ring", 
        ["count"]=1
    }, 
    [4]={
        ["log_name"]="flamma manopolas +2", 
        ["id"]=25835, 
        ["name"]="flam. manopolas +2", 
        ["count"]=1
    }, 
    [5]={
        ["log_name"]="ankou's mantle", 
        ["count"]=1, 
        ["id"]=26253, 
        ["name"]="ankou's mantle", 
        ["augments"]={
            [1]="DEX+20", 
            [2]="Accuracy+20 Attack+20", 
            [3]="Accuracy+10", 
            [4]="\"Dbl.Atk.\"+10", 
            [5]="Phys. dmg. taken-10%"
        }
    }, 
    [6]={
        ["log_name"]="ankou's mantle", 
        ["count"]=1, 
        ["id"]=26253, 
        ["name"]="ankou's mantle", 
        ["augments"]={
            [1]="STR+20", 
            [2]="Accuracy+20 Attack+20", 
            [3]="STR+10", 
            [4]="Weapon skill damage +10%"
        }
    }, 
    [7]={
        ["log_name"]="flamma zucchetto +2", 
        ["id"]=25569, 
        ["name"]="flam. zucchetto +2", 
        ["count"]=1
    }, 
    [8]={
        ["log_name"]="flamma gambieras +2", 
        ["id"]=25953, 
        ["name"]="flam. gambieras +2", 
        ["count"]=1
    }, 
    [9]={
        ["log_name"]="montante +1", 
        ["id"]=21689, 
        ["name"]="montante +1", 
        ["count"]=1
    }
}