sets.exported={
    main="Kaja Sword",
    sub="Genmei Shield",
    ammo="Hydrocera",
    head={ name="Vanya Hood", augments={'MP+50','"Cure" potency +7%','Enmity-6',}},
    body="Jhakri Robe",
    hands="Jhakri Cuffs +1",
    legs={ name="Carmine Cuisses +1", augments={'Accuracy+20','Attack+12','"Dual Wield"+6',}},
    feet="Aya. Gambieras +2",
    neck="Loricate Torque +1",
    waist="Sailfi Belt +1",
    left_ear="Mendi. Earring",
    right_ear="Influx Earring",
    left_ring="Kishar Ring",
    right_ring="Jhakri Ring",
    back={ name="Sucellos's Cape", augments={'DEX+20','Accuracy+10 Attack+10','Accuracy+5','"Dbl.Atk."+10','Phys. dmg. taken-10%',}},
}