sets.exported={
    main="Demers. Degen +1",
    sub="Ternion Dagger",
    ammo="Hydrocera",
    head="Jhakri Coronal",
    body="Jhakri Robe",
    hands="Jhakri Cuffs +1",
    legs={ name="Carmine Cuisses +1", augments={'Accuracy+20','Attack+12','"Dual Wield"+6',}},
    feet="Aya. Gambieras",
    neck="Loricate Torque +1",
    waist="Sailfi Belt +1",
    left_ear="Aredan Earring",
    right_ear="Influx Earring",
    left_ring="Ilabrat Ring",
    right_ring="Jhakri Ring",
    back={ name="Sucellos's Cape", augments={'DEX+20','Accuracy+10 Attack+10','"Dbl.Atk."+10',}},
}