sets.exported={
    main="Demers. Degen +1",
    sub="Genmei Shield",
    ammo="Hydrocera",
    head="Aya. Zucchetto",
    body="Jhakri Robe",
    hands="Aya. Manopolas",
    legs={ name="Carmine Cuisses +1", augments={'Accuracy+20','Attack+12','"Dual Wield"+6',}},
    feet="Aya. Gambieras",
    neck="Loricate Torque +1",
    waist="Sailfi Belt +1",
    left_ear="Sherida Earring",
    right_ear="Dominance Earring",
    left_ring="Ilabrat Ring",
    right_ring="Apate Ring",
    back={ name="Sucellos's Cape", augments={'DEX+20','Accuracy+10 Attack+10',}},
}