-- Generated by the Organizer Library (Wed May 31 19:37:04 2023)
return {
    [1]={
        ["log_name"]="wax sword", 
        ["id"]=16600, 
        ["name"]="wax sword", 
        ["count"]=1
    }, 
    [2]={
        ["log_name"]="flamma korazin +2", 
        ["id"]=25797, 
        ["name"]="flamma korazin +2", 
        ["count"]=1
    }, 
    [3]={
        ["log_name"]="flamma manopolas +2", 
        ["id"]=25835, 
        ["name"]="flam. manopolas +2", 
        ["count"]=1
    }, 
    [4]={
        ["log_name"]="flamma zucchetto +2", 
        ["id"]=25569, 
        ["name"]="flam. zucchetto +2", 
        ["count"]=1
    }, 
    [5]={
        ["log_name"]="flamma dirs +2", 
        ["id"]=25886, 
        ["name"]="flamma dirs +2", 
        ["count"]=1
    }, 
    [6]={
        ["log_name"]="flamma gambieras +2", 
        ["id"]=25953, 
        ["name"]="flam. gambieras +2", 
        ["count"]=1
    }
}