-- Generated by the Organizer Library (Sun Jul 23 06:33:37 2023)
return {
    [1]={
        ["log_name"]="bronze dagger", 
        ["id"]=16448, 
        ["name"]="bronze dagger", 
        ["count"]=1
    }, 
    [2]={
        ["log_name"]="bronze zaghnal", 
        ["id"]=16768, 
        ["name"]="bronze zaghnal", 
        ["count"]=1
    }, 
    [3]={
        ["log_name"]="harpoon", 
        ["id"]=16832, 
        ["name"]="harpoon", 
        ["count"]=1
    }, 
    [4]={
        ["log_name"]="wax sword", 
        ["id"]=16600, 
        ["name"]="wax sword", 
        ["count"]=1
    }, 
    [5]={
        ["log_name"]="cobra staff", 
        ["id"]=18614, 
        ["name"]="cobra staff", 
        ["count"]=1
    }, 
    [6]={
        ["log_name"]="mutsunokami", 
        ["id"]=21977, 
        ["name"]="mutsunokami", 
        ["count"]=1
    }, 
    [7]={
        ["log_name"]="kitty rod", 
        ["id"]=18871, 
        ["name"]="kitty rod", 
        ["count"]=1
    }, 
    [8]={
        ["log_name"]="trainee burin", 
        ["id"]=19274, 
        ["name"]="trainee burin", 
        ["count"]=1
    }, 
    [9]={
        ["log_name"]="warder's charm +1", 
        ["id"]=27505, 
        ["name"]="warder's charm +1", 
        ["count"]=1
    }, 
    [10]={
        ["log_name"]="goujian", 
        ["id"]=21680, 
        ["name"]="goujian", 
        ["count"]=1
    }
}