-- Generated by the Organizer Library (Sat Apr 13 07:04:31 2024)
return {
    [1]={
        ["log_name"]="stikini ring +1", 
        ["id"]=26184, 
        ["name"]="stikini ring +1", 
        ["count"]=1
    }, 
    [2]={
        ["log_name"]="soulflayer's wand", 
        ["id"]=22004, 
        ["name"]="soulflayer's wand", 
        ["count"]=1
    }, 
    [3]={
        ["log_name"]="merlinic dastanas", 
        ["count"]=1, 
        ["id"]=27141, 
        ["name"]="merlinic dastanas", 
        ["augments"]={
            [1]="Attack+17", 
            [2]="Pet: INT+5", 
            [3]="\"Refresh\"+2", 
            [4]="Accuracy+11 Attack+11"
        }
    }, 
    [4]={
        ["log_name"]="thereoid greaves", 
        ["id"]=27503, 
        ["name"]="thereoid greaves", 
        ["count"]=1
    }, 
    [5]={
        ["log_name"]="merlinic jubbah", 
        ["count"]=1, 
        ["id"]=25719, 
        ["name"]="merlinic jubbah", 
        ["augments"]={
            [1]="Mag. Acc.+22 \"Mag.Atk.Bns.\"+22", 
            [2]="\"Occult Acumen\"+4", 
            [3]="INT+10", 
            [4]="Mag. Acc.+2", 
            [5]="\"Mag.Atk.Bns.\"+15"
        }
    }, 
    [6]={
        ["log_name"]="merlinic hood", 
        ["count"]=1, 
        ["id"]=25643, 
        ["name"]="merlinic hood", 
        ["augments"]={
            [1]="Mag. Acc.+21 \"Mag.Atk.Bns.\"+21", 
            [2]="INT+15", 
            [3]="Mag. Acc.+3", 
            [4]="\"Mag.Atk.Bns.\"+13"
        }
    }
}