-- Generated by the Organizer Library (Sat Apr 13 07:04:31 2024)
return {
    [1]={
        ["log_name"]="baetyl pendant", 
        ["id"]=26003, 
        ["name"]="baetyl pendant", 
        ["count"]=1
    }, 
    [2]={
        ["log_name"]="halitus helm", 
        ["id"]=25653, 
        ["name"]="halitus helm", 
        ["count"]=1
    }, 
    [3]={
        ["log_name"]="lissome necklace", 
        ["id"]=26004, 
        ["name"]="lissome necklace", 
        ["count"]=1
    }, 
    [4]={
        ["log_name"]="mizukage-no-kubikazari", 
        ["id"]=28379, 
        ["name"]="mizu. kubikazari", 
        ["count"]=1
    }, 
    [5]={
        ["log_name"]="lengo pants", 
        ["id"]=27321, 
        ["name"]="lengo pants", 
        ["count"]=1
    }, 
    [6]={
        ["log_name"]="merlinic shalwar", 
        ["id"]=25843, 
        ["name"]="merlinic shalwar", 
        ["count"]=1
    }, 
    [7]={
        ["log_name"]="staunch tathlum +1", 
        ["id"]=22279, 
        ["name"]="staunch tathlum +1", 
        ["count"]=1
    }, 
    [8]={
        ["log_name"]="rubicundity", 
        ["id"]=21089, 
        ["name"]="rubicundity", 
        ["count"]=1
    }, 
    [9]={
        ["log_name"]="siegel sash", 
        ["id"]=15960, 
        ["name"]="siegel sash", 
        ["count"]=1
    }, 
    [10]={
        ["log_name"]="volte gaiters", 
        ["id"]=23726, 
        ["name"]="volte gaiters", 
        ["count"]=1
    }
}