-- Generated by the Organizer Library (Sat Apr 13 07:04:31 2024)
return {
    [1]={
        ["log_name"]="fotia belt", 
        ["id"]=28420, 
        ["name"]="fotia belt", 
        ["count"]=1
    }, 
    [2]={
        ["log_name"]="eschan stone", 
        ["id"]=28415, 
        ["name"]="eschan stone", 
        ["count"]=1
    }, 
    [3]={
        ["log_name"]="freke ring", 
        ["id"]=28472, 
        ["name"]="freke ring", 
        ["count"]=1
    }, 
    [4]={
        ["log_name"]="reiki yotai", 
        ["id"]=26321, 
        ["name"]="reiki yotai", 
        ["count"]=1
    }, 
    [5]={
        ["log_name"]="crocea mors", 
        ["id"]=21627, 
        ["name"]="crocea mors", 
        ["count"]=1
    }, 
    [6]={
        ["log_name"]="twilight cloak", 
        ["id"]=11363, 
        ["name"]="twilight cloak", 
        ["count"]=1
    }, 
    [7]={
        ["log_name"]="ayanmo manopolas +2", 
        ["id"]=25833, 
        ["name"]="aya. manopolas +2", 
        ["count"]=1
    }, 
    [8]={
        ["log_name"]="combatant's torque", 
        ["id"]=26015, 
        ["name"]="combatant's torque", 
        ["count"]=1
    }, 
    [9]={
        ["log_name"]="mujin band", 
        ["id"]=11672, 
        ["name"]="mujin band", 
        ["count"]=1
    }, 
    [10]={
        ["log_name"]="psycloth lappas", 
        ["id"]=27287, 
        ["name"]="psycloth lappas", 
        ["count"]=1
    }, 
    [11]={
        ["log_name"]="incanter's torque", 
        ["id"]=26016, 
        ["name"]="incanter's torque", 
        ["count"]=1
    }, 
    [12]={
        ["log_name"]="ceremonial dagger", 
        ["id"]=16753, 
        ["name"]="ceremonial dagger", 
        ["count"]=1
    }, 
    [13]={
        ["log_name"]="dignitary's earring", 
        ["id"]=27547, 
        ["name"]="digni. earring", 
        ["count"]=1
    }, 
    [14]={
        ["log_name"]="qutrub knife", 
        ["id"]=20576, 
        ["name"]="qutrub knife", 
        ["count"]=1
    }, 
    [15]={
        ["log_name"]="maxentius", 
        ["id"]=22031, 
        ["name"]="maxentius", 
        ["count"]=1
    }, 
    [16]={
        ["log_name"]="warder's charm +1", 
        ["id"]=27505, 
        ["name"]="warder's charm +1", 
        ["count"]=1
    }, 
    [17]={
        ["log_name"]="suppanomimi", 
        ["id"]=14739, 
        ["name"]="suppanomimi", 
        ["count"]=1
    }, 
    [18]={
        ["log_name"]="epaminondas's ring", 
        ["id"]=26214, 
        ["name"]="epaminondas's ring", 
        ["count"]=1
    }, 
    [19]={
        ["log_name"]="hachirin-no-obi", 
        ["id"]=28419, 
        ["name"]="hachirin-no-obi", 
        ["count"]=1
    }, 
    [20]={
        ["log_name"]="telos earring", 
        ["id"]=27545, 
        ["name"]="telos earring", 
        ["count"]=1
    }, 
    [21]={
        ["log_name"]="twilight cape", 
        ["id"]=16259, 
        ["name"]="twilight cape", 
        ["count"]=1
    }, 
    [22]={
        ["log_name"]="ammurapi shield", 
        ["id"]=26419, 
        ["name"]="ammurapi shield", 
        ["count"]=1
    }, 
    [23]={
        ["log_name"]="perimede cape", 
        ["id"]=26243, 
        ["name"]="perimede cape", 
        ["count"]=1
    }, 
    [24]={
        ["log_name"]="befouled crown", 
        ["id"]=26790, 
        ["name"]="befouled crown", 
        ["count"]=1
    }, 
    [25]={
        ["log_name"]="dedition earring", 
        ["id"]=27544, 
        ["name"]="dedition earring", 
        ["count"]=1
    }, 
    [26]={
        ["log_name"]="clerisy strap +1", 
        ["id"]=22201, 
        ["name"]="clerisy strap +1", 
        ["count"]=1
    }, 
    [27]={
        ["log_name"]="ethereal earring", 
        ["id"]=15965, 
        ["name"]="ethereal earring", 
        ["count"]=1
    }, 
    [28]={
        ["log_name"]="fotia gorget", 
        ["id"]=27510, 
        ["name"]="fotia gorget", 
        ["count"]=1
    }, 
    [29]={
        ["log_name"]="petrov ring", 
        ["id"]=10772, 
        ["name"]="petrov ring", 
        ["count"]=1
    }, 
    [30]={
        ["log_name"]="orpheus's sash", 
        ["id"]=26359, 
        ["name"]="orpheus's sash", 
        ["count"]=1
    }
}